spring.application.name=gateway
server.port=8083


logging.level.org.springframework.security=DEBUG

#jwt configuration
security.jwt.user.generator=microservicio-usuario
security.jwt.key.private=07ffe3e4d4be709cf62818494dd76a9249fd58e835338439bee1b2ccdc58f467

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.web.server=DEBUG

# Deshabilitar la creación de la página de login predeterminada
spring.security.oauth2.client.enable-default-login-page=false



# Rutas del gateway
spring.cloud.gateway.routes[0].id=microservicio-vuelos
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/flight/**

spring.cloud.gateway.routes[1].id=microservicio-usuario
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**






